# Generated by Django 5.1.3 on 2026-06-11 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glossary', '0007_alter_source_copyright_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='Hex color, e.g. #6e44ff', max_length=7)),
                ('weight', models.PositiveIntegerField(default=0, help_text='Ordering in compass/legend')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('human_framing', models.CharField(blank=True, help_text="One-line editorial frame for this year, in the author's voice.", max_length=300)),
                ('newsletter_url', models.URLField(blank=True)),
                ('newsletter_title', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Meta title', max_length=300)),
                ('description', models.CharField(blank=True, help_text='Meta description; 160 characters max.', max_length=160)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated based on title. Full URL visible after saving...', max_length=300, unique=True)),
                ('noindex_nofollow', models.BooleanField(default=False, help_text='Set the meta robots tag to noindex, nofollow')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('content_review', models.BooleanField(default=False)),
                ('visual_review', models.BooleanField(default=False)),
                ('seo_review', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False, help_text='Final approval. Must be checked for this page to be live.', verbose_name='Approved to Publish')),
                ('last_approval_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text="Where this sits on the timeline. May differ from the Source's publication date.")),
                ('date_precision', models.CharField(choices=[('exact', 'Exact date'), ('month', 'Month'), ('year', 'Year')], default='exact', max_length=10)),
                ('timeline_context', models.TextField(blank=True, help_text='Short framing for the timeline view (markdown). Detail content comes from linked Term/Source.')),
                ('kind', models.CharField(blank=True, choices=[('film', 'Film / TV'), ('book', 'Book / Publication'), ('tech', 'Technology'), ('event', 'Historical Event'), ('idea', 'Idea / Concept'), ('personal', 'Personal / Newsletter')], help_text="Leave blank to derive from linked Source's type.", max_length=20)),
                ('related_entries', models.ManyToManyField(blank=True, to='timeline.timelineentry')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to='glossary.source')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to='glossary.term')),
            ],
            options={
                'verbose_name_plural': 'timeline entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TimelineSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_review', models.BooleanField(default=False)),
                ('visual_review', models.BooleanField(default=False)),
                ('seo_review', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False, help_text='Final approval. Must be checked for this page to be live.', verbose_name='Approved to Publish')),
                ('last_approval_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Blank = ongoing.', null=True)),
                ('start_fuzzy', models.BooleanField(default=True)),
                ('end_fuzzy', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Markdown.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spans', to='timeline.spancategory')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_spans', to='glossary.term')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
