# Generated by Django 5.1.3 on 2025-09-13 19:06

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of the work as it will be displayed on site and in schema', max_length=300)),
                ('about', models.TextField(blank=True, help_text='The subject matter of the content.')),
                ('image', core.fields.OptimizedImageField(blank=True, upload_to='gallery/')),
                ('image_webp', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('date_artwork_created', models.DateTimeField(blank=True)),
                ('art_medium', models.CharField(blank=True, default='Charcoal', help_text='The material used (e.g. Oil, Watercolour, Acrylic, Woodcut, etc.', max_length=255)),
                ('art_edition', models.CharField(blank=True, help_text='The number of copies when multiple copies of a piece of artwork are produced - e.g. for a limited edition of 20 prints, \'artEdition\' refers to the total number of copies (in this example "20").', max_length=255)),
                ('artform', models.CharField(blank=True, default='Drawing', help_text='Painting, Drawing, Sculpture, Print, Photograph, Assemblage, Collage, etc.', max_length=255)),
                ('artwork_surface', models.CharField(blank=True, default='Paper', help_text='The supporting materials for the artwork, e.g. Canvas, Paper, Wood, Board, etc.', max_length=255)),
                ('height', models.PositiveIntegerField(blank=True)),
                ('width', models.PositiveIntegerField(blank=True)),
                ('dimension_unit', models.CharField(blank=True, choices=[('in', 'Inches'), ('ft', 'Feet')], max_length=50)),
                ('artist', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='author.author')),
            ],
        ),
    ]
