# Generated by Django 5.1.3 on 2025-09-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_artwork_date_artwork_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
