# Generated by Django 5.1.3 on 2025-09-13 22:19

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_workdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=core.fields.OptimizedImageField(blank=True, upload_to='images/gallery/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='images/gallery/'),
        ),
    ]
