# Generated by Django 5.1.3 on 2025-09-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_artwork_image_alter_artwork_image_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdetail',
            name='impact',
            field=models.TextField(blank=True, help_text='Extra content for using the piece.'),
        ),
    ]
