# Generated by Django 5.1.3 on 2025-09-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_workdetail_impact'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Purchase Digital', max_length=50)),
                ('link', models.CharField(max_length=500)),
                ('template', models.CharField(choices=[('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-text', 'Text Button / Link')], max_length=50)),
                ('work_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='gallery.workdetail')),
            ],
        ),
    ]
