# Generated by Django 5.1.3 on 2025-10-11 22:18

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_workbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Meta title', max_length=300)),
                ('description', models.CharField(blank=True, help_text='Meta description; 160 characters max.', max_length=160)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated based on title. Full URL visible after saving...', max_length=300, unique=True)),
                ('noindex_nofollow', models.BooleanField(default=False, help_text='Set the meta robots tag to noindex, nofollow')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('content_review', models.BooleanField(default=False)),
                ('visual_review', models.BooleanField(default=False)),
                ('seo_review', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False, help_text='Final approval. Must be checked for this page to be live.', verbose_name='Approved to Publish')),
                ('last_approval_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Title of the work as it will be displayed on site and in schema', max_length=300)),
                ('about', models.TextField(blank=True, help_text='The subject matter of the content.')),
                ('image', core.fields.OptimizedImageField(blank=True, upload_to='images/gallery/exhibit/%Y/%m/')),
                ('image_webp', models.ImageField(blank=True, null=True, upload_to='images/gallery/exhibit/%Y/%m/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExhibitWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.artwork')),
                ('exhibit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.exhibit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
