# Generated by Django 5.1.3 on 2025-10-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_exhibit_exhibitwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='name',
            field=models.CharField(blank=True, help_text='Title of the exhibit as it will be displayed on site and in schema', max_length=300),
        ),
    ]
