# Generated by Django 5.1.3 on 2024-12-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='headline',
        ),
    ]
