# Generated by Django 5.1.3 on 2025-01-12 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('newsletter', '0003_remove_newsletter_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='author.author'),
        ),
    ]
