# Generated by Django 5.1.3 on 2025-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_sourceauthor_source_termsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='date_modified',
            field=models.DateField(blank=True, help_text="The date on which the CreativeWork was most recently modified or when the item's entry was modified within a DataFeed.", null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='date_published',
            field=models.DateField(blank=True, help_text='Date of first publication or broadcast.', null=True),
        ),
    ]
