# Generated by Django 5.1.3 on 2025-08-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_source_date_modified_source_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsource',
            name='page_number',
            field=models.CharField(blank=True, help_text='Number or range', max_length=50),
        ),
    ]
