# Generated by Django 5.1.3 on 2025-08-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0004_termsource_page_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Person or organization full name', max_length=300)),
                ('is_organization', models.BooleanField(default=True, help_text='If publisher is an person, uncheck. This reflects in the publisher schema that it is a Person rather than the more typical Organization.')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.sourcepublisher'),
        ),
    ]
