# Generated by Django 5.1.3 on 2025-08-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0005_sourcepublisher_source_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='alt_title',
            field=models.CharField(blank=True, help_text='This will be the shorter version of the title for secondary references in footnotes.', max_length=500),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(help_text="Use the full title / headline, including the subheadline. Exp: include the part after the ':'", max_length=500),
        ),
    ]
