# Generated by Django 5.1.3 on 2025-08-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0006_source_alt_title_alter_source_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='copyright_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
