# Generated by Django 5.1.3 on 2026-09-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0007_alter_source_copyright_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='creative_work_type',
            field=models.CharField(choices=[('Book', 'Book'), ('Article', 'Article'), ('ScholarlyArticle', 'Scholarly Article'), ('NewsArticle', 'News Article'), ('Movie', 'Movie'), ('TVSeries', 'TV Series'), ('WebSite', 'Website'), ('WebPage', 'Webpage'), ('CreativeWork', 'Creative Work'), ('SocialMediaPosting', 'Social Media Posting'), ('Photograph', 'Photograph'), ('Painting', 'Painting'), ('PodcastSeries', 'Podcast Series'), ('PodcastEpisode', 'Podcast Episode'), ('RadioSeries', 'Radio Series'), ('MusicRecording', 'Music Recording'), ('MusicGroup', 'Music Group'), ('VideoGame', 'Video Game')], max_length=50),
        ),
    ]
