# Generated by Django 5.1.3 on 2025-02-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Meta title', max_length=300)),
                ('description', models.CharField(blank=True, help_text='Meta description; 160 characters max.', max_length=160)),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated based on title. Full URL visible after saving...', max_length=300, unique=True)),
                ('noindex_nofollow', models.BooleanField(default=False, help_text='Set the meta robots tag to noindex, nofollow')),
                ('content_review', models.BooleanField(default=False)),
                ('visual_review', models.BooleanField(default=False)),
                ('seo_review', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False, help_text='Final approval. Must be checked for this page to be live.', verbose_name='Approved to Publish')),
                ('last_approval_date', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
