# Generated by Django 5.1.3 on 2025-08-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glossary', '0006_source_alt_title_alter_source_title'),
        ('newsletter', '0006_alter_newsletter_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, help_text="Uncheck to remove from the page's rail.")),
                ('glossary_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.term')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_links', to='newsletter.newsletter')),
            ],
            options={
                'unique_together': {('newsletter', 'glossary_term')},
            },
        ),
    ]
