# Generated by Django 5.1.3 on 2025-08-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0006_source_alt_title_alter_source_title'),
        ('newsletter', '0006_alter_newsletter_tags'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendedlink',
            old_name='glossary_term',
            new_name='term',
        ),
        migrations.AlterUniqueTogether(
            name='recommendedlink',
            unique_together={('newsletter', 'term')},
        ),
    ]
