# Generated by Django 5.1.3 on 2024-11-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Upgrade your humanity.', max_length=255)),
                ('subheadline', models.CharField(default='Lessons learned about humans through technology and systems...and vice versa', max_length=255)),
            ],
        ),
    ]
