# Generated by Django 5.1.3 on 2025-02-18 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_homeherobutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.CharField(blank=True, help_text='Meta description; 160 characters max.', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='noindex_nofollow',
            field=models.BooleanField(default=False, help_text='Set the meta robots tag to noindex, nofollow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated based on title. Full URL visible after saving...', max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='CYBORG_ Newsletter', help_text='Meta title', max_length=300),
            preserve_default=False,
        ),
    ]
